apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculation-1-test-advanced
  name: calculation-1-test-advanced
spec:
  replicas: 1
  # strategy: {}
  selector:
    matchLabels:
      app: calculation-1-test-advanced
  template:
    metadata:
      labels:
        app: calculation-1-test-advanced
    spec:
      containers:
      - image: troublemaker777/bachelor:distributed-calculation
        name: calculation-1-test-advanced
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculation-1-test-advanced
  name: calculation-1-test-advanced
spec:
  ports:
  - name: http
    nodePort: 30011
    port: 8080
    targetPort: 8080
  selector:
    app: calculation-1-test-advanced
# status:
#   loadBalancer: {}

