apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: distributed-calculation-f3
spec:
  hosts:
  - distributed-calculation.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
    - destination:
        host: distributed-calculation.default.svc.cluster.local
        subset: v1
  - route:
    - destination:
        host: distributed-calculation.default.svc.cluster.local
        subset: v2