apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: control
  name: control
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: control
  template:
    metadata:
      labels:
        app: control
    spec:
      containers:
      - image: troublemaker777/bachelor:control
        name: control
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: control
  name: control
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30000
    targetPort: 8080
  selector:
    app: control
status:
  loadBalancer: {}

