apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-repository
  name: service-repository
spec:
  type: NodePort
  ports:
  - name: "7000"
    port: 8080
    nodePort: 30005
    targetPort: 8080
  selector:
    app: service-repository
status:
  loadBalancer: {}

