apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: distributed-calculation-outlier
spec:
  host: distributed-calculation.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 60s
      consecutiveErrors: 3
      interval: 20s
      maxEjectionPercent: 100


      