apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: distributed-calculation
spec:
  hosts:
    - distributed-calculation.default.svc.cluster.local
  http:
    - route:
        - destination:
            host: distributed-calculation.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: billing
spec:
  hosts:
    - billing.default.svc.cluster.local
  http:
    - route:
        - destination:
            host: billing.default.svc.cluster.local
---




